apiVersion: v1
kind: Namespace
metadata:
  name: llm-multiroute-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-multiroute-app
  namespace: llm-multiroute-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-multiroute
  template:
    metadata:
      labels:
        app: llm-multiroute
    spec:
      containers:
        - name: api
          image: harshitagarwal/llm-multiroute:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_BASE_URL
              value: http://host.docker.internal:11434
---
apiVersion: v1
kind: Service
metadata:
  name: llm-multiroute-service
  namespace: llm-multiroute-backend
spec:
  selector:
    app: llm-multiroute
  ports:
    - port: 8080
      targetPort: 8080
